- uses: quartx-analytics/ghcr-cleaner@v1
  with:
      owner-type: org # or user
      token: ${{ secrets.PAT_TOKEN }}
      repository_owner: ${{ github.repository_owner }}
      delete-untagged: true
